services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://dazah-backend-app-1:8000
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - CHOKIDAR_USEPOLLING=true
    user: "node"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend
    command: sh -c "rm -rf /app/.next && pnpm dev"
    restart: unless-stopped

  ci-build:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm build
    environment:
      - API_BASE_URL=http://dazah-backend-app-1:8000
    volumes:
      - /app/node_modules
    networks:
      - backend

networks:
  backend:
    external: true
    name: ${BACKEND_NETWORK:-dazah-backend_default}
