"""add equipment department scoping and safety enhancements

Revision ID: acf93d19aaa4
Revises: 0006_quality_qms_sop_ai
Create Date: 2026-07-07 14:22:07.671721
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007_equipment_safety'
down_revision: Union[str, None] = '0006_quality_qms_sop_ai'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS equipment')
    op.execute('CREATE SCHEMA IF NOT EXISTS permission')
    op.execute('CREATE SCHEMA IF NOT EXISTS quality')
    op.execute('CREATE SCHEMA IF NOT EXISTS safety')
    op.create_table('sop_ai_check_main',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('file_code', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=False),
    sa.Column('risk_high', sa.Integer(), nullable=False),
    sa.Column('risk_medium', sa.Integer(), nullable=False),
    sa.Column('risk_low', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sop_ai_check_main_created_at', 'sop_ai_check_main', ['created_at'], unique=False)
    op.create_index('ix_sop_ai_check_main_file_code', 'sop_ai_check_main', ['file_code'], unique=False)
    op.create_index('ix_sop_ai_check_main_status', 'sop_ai_check_main', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码，如 equipment:inspection:create'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='显示名称，如 创建巡检'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块编码'),
    sa.Column('resource', sa.String(length=50), nullable=False, comment='资源类型'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型: read/create/update/delete/approve/manage'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='系统内置权限不可删除'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_permission_permissions_code'),
    schema='permission'
    )
    op.create_table('role_data_scope_overrides',
    sa.Column('role_id', sa.Uuid(), nullable=False, comment='角色 ID'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='模块编码'),
    sa.Column('data_scope', sa.String(length=30), nullable=False, comment='覆盖后的数据范围'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module', name='uq_role_data_scope_module'),
    schema='permission'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.Uuid(), nullable=False, comment='权限 ID'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_pair'),
    schema='permission'
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码，如 equipment_inspector'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_scope', sa.String(length=30), server_default='department', nullable=False, comment='默认数据范围: all/department/department_and_children/self_only'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='系统内置角色不可删除'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_permission_roles_code'),
    schema='permission'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='用户 ID (identity.users)'),
    sa.Column('role_id', sa.Uuid(), nullable=False, comment='角色 ID'),
    sa.Column('department_id', sa.Uuid(), nullable=True, comment='可选：限定角色在某部门生效，NULL=全局'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'department_id', name='uq_user_roles_triple'),
    schema='permission'
    )
    op.create_table('sop_ai_check_problem',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('main_id', sa.String(length=36), nullable=False),
    sa.Column('problem_type', sa.Enum('DUPLICATE', 'CONFLICT', 'COMPLIANCE', 'FORMAT', 'CONTENT', name='problemtype'), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('handle_status', sa.Enum('PENDING', 'CONFIRMED', 'IGNORED', 'FIXED', name='handlestatus'), nullable=False),
    sa.Column('ignore_reason', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['main_id'], ['sop_ai_check_main.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sop_ai_check_problem_handle_status', 'sop_ai_check_problem', ['handle_status'], unique=False)
    op.create_index('ix_sop_ai_check_problem_main_id', 'sop_ai_check_problem', ['main_id'], unique=False)
    op.create_index('ix_sop_ai_check_problem_risk_level', 'sop_ai_check_problem', ['risk_level'], unique=False)
    op.create_table('sop_ai_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.add_column('equipment_categories', sa.Column('department_id', sa.Uuid(), nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index(op.f('uq_equipment_categories_code'), table_name='equipment_categories', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_equipment_categories_code_dept', 'equipment_categories', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_category_links'), 'equipment_category_links', schema='equipment', type_='unique')
    op.create_index('uq_equipment_category_links', 'equipment_category_links', ['equipment_id', 'category_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', schema='equipment', type_='unique')
    op.create_index('uq_equipment_personnel_category', 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', schema='equipment', type_='unique')
    op.create_index('uq_equipment_personnel_role', 'equipment_personnel_role', ['personnel_id', 'role_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_role_code'), 'equipment_role', schema='equipment', type_='unique')
    op.create_index('uq_equipment_role_code', 'equipment_role', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipments_equipment_no'), 'equipments', schema='equipment', type_='unique')
    op.create_index('uq_equipments_equipment_no', 'equipments', ['equipment_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', schema='equipment', type_='unique')
    op.create_index('uq_route_equipments_route_equipment', 'inspection_route_equipments', ['route_id', 'equipment_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', schema='equipment', type_='unique')
    op.create_index('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', ['route_id', 'cron_expression'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_inspection_routes_name'), 'inspection_routes', schema='equipment', type_='unique')
    op.create_index('uq_inspection_routes_name', 'inspection_routes', ['name'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', schema='equipment', type_='unique')
    op.create_index('uq_inspection_tasks_task_no', 'inspection_tasks', ['task_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.add_column('locations', sa.Column('department_id', sa.Uuid(), nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index(op.f('uq_locations_code'), table_name='locations', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_locations_code_dept', 'locations', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_work_orders_work_order_no'), 'work_orders', schema='equipment', type_='unique')
    op.create_index('uq_work_orders_work_order_no', 'work_orders', ['work_order_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.add_column('hazard_reports', sa.Column('defect_substance', sa.String(length=32), nullable=True, comment='缺陷实质评估: substantive / procedural / uncertain'), schema='safety')
    op.add_column('hazard_reports', sa.Column('defect_substance_reasoning', sa.Text(), nullable=True, comment='缺陷实质评估理由'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hazard_reports', 'defect_substance_reasoning', schema='safety')
    op.drop_column('hazard_reports', 'defect_substance', schema='safety')
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-07 06:21:41.030766+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.drop_index('uq_work_orders_work_order_no', table_name='work_orders', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_work_orders_work_order_no'), 'work_orders', ['work_order_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_locations_code_dept', table_name='locations', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_locations_code'), 'locations', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('locations', 'department_id', schema='equipment')
    op.drop_index('uq_inspection_tasks_task_no', table_name='inspection_tasks', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', ['task_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_inspection_routes_name', table_name='inspection_routes', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_inspection_routes_name'), 'inspection_routes', ['name', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_route_schedules_route_cron_deleted', table_name='inspection_route_schedules', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', ['route_id', 'cron_expression', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_route_equipments_route_equipment', table_name='inspection_route_equipments', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', ['route_id', 'equipment_id', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipments_equipment_no', table_name='equipments', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipments_equipment_no'), 'equipments', ['equipment_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_role_code', table_name='equipment_role', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_role_code'), 'equipment_role', ['code'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_personnel_role', table_name='equipment_personnel_role', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', ['personnel_id', 'role_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_personnel_category', table_name='equipment_personnel_category', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_category_links', table_name='equipment_category_links', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_category_links'), 'equipment_category_links', ['equipment_id', 'category_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_categories_code_dept', table_name='equipment_categories', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_equipment_categories_code'), 'equipment_categories', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('equipment_categories', 'department_id', schema='equipment')
    op.drop_table('sop_ai_config')
    op.drop_index('ix_sop_ai_check_problem_risk_level', table_name='sop_ai_check_problem')
    op.drop_index('ix_sop_ai_check_problem_main_id', table_name='sop_ai_check_problem')
    op.drop_index('ix_sop_ai_check_problem_handle_status', table_name='sop_ai_check_problem')
    op.drop_table('sop_ai_check_problem')
    op.drop_table('user_roles', schema='permission')
    op.drop_table('roles', schema='permission')
    op.drop_table('role_permissions', schema='permission')
    op.drop_table('role_data_scope_overrides', schema='permission')
    op.drop_table('permissions', schema='permission')
    op.drop_index('ix_sop_ai_check_main_status', table_name='sop_ai_check_main')
    op.drop_index('ix_sop_ai_check_main_file_code', table_name='sop_ai_check_main')
    op.drop_index('ix_sop_ai_check_main_created_at', table_name='sop_ai_check_main')
    op.drop_table('sop_ai_check_main')
    # ### end Alembic commands ###
