"""add_core_module_tables

Revision ID: d4ef21aad03d
Revises: f1a2b3c4d5e6
Create Date: 2026-07-07 16:59:44.832769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0016_add_core_module_tables'
down_revision: Union[str, None] = '0015_add_procurement_contract_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS core')
    op.drop_index(op.f('ix_core_agent_tool_calls_operation'), table_name='agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_tool_calls_session_id'), table_name='agent_tool_calls', schema='core')
    op.drop_table('agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_sessions_user_id'), table_name='agent_sessions', schema='core')
    op.drop_table('agent_sessions', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_session_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_status'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_user_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_workflow_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_table('agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_operation'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_session_id'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_user_id'), table_name='agent_confirmations', schema='core')
    op.drop_table('agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_name'), table_name='agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_status'), table_name='agent_skills', schema='core')
    op.drop_table('agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_session_id'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_status'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_user_id'), table_name='agent_workflows', schema='core')
    op.drop_table('agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_messages_session_id'), table_name='agent_messages', schema='core')
    op.drop_table('agent_messages', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('agent_messages_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('agent_messages_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_messages_pkey')),
    schema='core',
    comment='Agent conversation messages'
    )
    op.create_index(op.f('ix_core_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False, schema='core')
    op.create_table('agent_workflows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'enabled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('trigger_phrases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('source_skill', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('source_request', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_workflows_pkey')),
    schema='core',
    comment='Agent user workflow definitions'
    )
    op.create_index(op.f('ix_core_agent_workflows_user_id'), 'agent_workflows', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_status'), 'agent_workflows', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_session_id'), 'agent_workflows', ['session_id'], unique=False, schema='core')
    op.create_table('agent_skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trigger_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_builtin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_skills_pkey')),
    sa.UniqueConstraint('name', name=op.f('uq_core_agent_skills_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core',
    comment='Agent progressive disclosure skills'
    )
    op.create_index(op.f('ix_core_agent_skills_status'), 'agent_skills', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_skills_name'), 'agent_skills', ['name'], unique=False, schema='core')
    op.create_table('agent_confirmations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=32), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('agent_confirmations_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('agent_confirmations_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_confirmations_pkey')),
    schema='core',
    comment='Agent write operation confirmations'
    )
    op.create_index(op.f('ix_core_agent_confirmations_user_id'), 'agent_confirmations', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_session_id'), 'agent_confirmations', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_operation'), 'agent_confirmations', ['operation'], unique=False, schema='core')
    op.create_table('agent_workflow_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('steps_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('step_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_workflow_runs_pkey')),
    schema='core',
    comment='Agent workflow run state'
    )
    op.create_index(op.f('ix_core_agent_workflow_runs_workflow_id'), 'agent_workflow_runs', ['workflow_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_user_id'), 'agent_workflow_runs', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_status'), 'agent_workflow_runs', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_session_id'), 'agent_workflow_runs', ['session_id'], unique=False, schema='core')
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('agent_sessions_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('agent_sessions_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_sessions_pkey')),
    schema='core',
    comment='Agent conversation sessions'
    )
    op.create_index(op.f('ix_core_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False, schema='core')
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'started'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('agent_tool_calls_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('agent_tool_calls_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_tool_calls_pkey')),
    schema='core',
    comment='Agent tool execution audit'
    )
    op.create_index(op.f('ix_core_agent_tool_calls_session_id'), 'agent_tool_calls', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_tool_calls_operation'), 'agent_tool_calls', ['operation'], unique=False, schema='core')
    # ### end Alembic commands ###
