"""add_equipment_module_tables

Revision ID: c265526a0530
Revises: d4ef21aad03d
Create Date: 2026-07-07 17:01:37.369258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017_add_equipment_module_tables'
down_revision: Union[str, None] = '0016_add_core_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS equipment')
    op.add_column('equipment_categories', sa.Column('department_id', sa.Uuid(), nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index(op.f('uq_equipment_categories_code'), table_name='equipment_categories', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_equipment_categories_code_dept', 'equipment_categories', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_category_links'), 'equipment_category_links', schema='equipment', type_='unique')
    op.create_index('uq_equipment_category_links', 'equipment_category_links', ['equipment_id', 'category_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', schema='equipment', type_='unique')
    op.create_index('uq_equipment_personnel_category', 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', schema='equipment', type_='unique')
    op.create_index('uq_equipment_personnel_role', 'equipment_personnel_role', ['personnel_id', 'role_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipment_role_code'), 'equipment_role', schema='equipment', type_='unique')
    op.create_index('uq_equipment_role_code', 'equipment_role', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_equipments_equipment_no'), 'equipments', schema='equipment', type_='unique')
    op.create_index('uq_equipments_equipment_no', 'equipments', ['equipment_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', schema='equipment', type_='unique')
    op.create_index('uq_route_equipments_route_equipment', 'inspection_route_equipments', ['route_id', 'equipment_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', schema='equipment', type_='unique')
    op.create_index('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', ['route_id', 'cron_expression'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_inspection_routes_name'), 'inspection_routes', schema='equipment', type_='unique')
    op.create_index('uq_inspection_routes_name', 'inspection_routes', ['name'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', schema='equipment', type_='unique')
    op.create_index('uq_inspection_tasks_task_no', 'inspection_tasks', ['task_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.add_column('locations', sa.Column('department_id', sa.Uuid(), nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index(op.f('uq_locations_code'), table_name='locations', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_locations_code_dept', 'locations', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('uq_work_orders_work_order_no'), 'work_orders', schema='equipment', type_='unique')
    op.create_index('uq_work_orders_work_order_no', 'work_orders', ['work_order_no'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_work_orders_work_order_no', table_name='work_orders', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_work_orders_work_order_no'), 'work_orders', ['work_order_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_locations_code_dept', table_name='locations', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_locations_code'), 'locations', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('locations', 'department_id', schema='equipment')
    op.drop_index('uq_inspection_tasks_task_no', table_name='inspection_tasks', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', ['task_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_inspection_routes_name', table_name='inspection_routes', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_inspection_routes_name'), 'inspection_routes', ['name', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_route_schedules_route_cron_deleted', table_name='inspection_route_schedules', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', ['route_id', 'cron_expression', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_route_equipments_route_equipment', table_name='inspection_route_equipments', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', ['route_id', 'equipment_id', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipments_equipment_no', table_name='equipments', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipments_equipment_no'), 'equipments', ['equipment_no', 'is_deleted'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_role_code', table_name='equipment_role', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_role_code'), 'equipment_role', ['code'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_personnel_role', table_name='equipment_personnel_role', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', ['personnel_id', 'role_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_personnel_category', table_name='equipment_personnel_category', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_category_links', table_name='equipment_category_links', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_equipment_category_links'), 'equipment_category_links', ['equipment_id', 'category_id'], schema='equipment', postgresql_nulls_not_distinct=False)
    op.drop_index('uq_equipment_categories_code_dept', table_name='equipment_categories', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_equipment_categories_code'), 'equipment_categories', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('equipment_categories', 'department_id', schema='equipment')
    # ### end Alembic commands ###
