"""add_permission_module_tables

Revision ID: 0018_add_permission_module_tables
Revises: 0018_add_hr_module_tables
Create Date: 2026-07-07 17:01:51.578420
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0018_add_permission_module_tables'
down_revision: Union[str, None] = '0017_add_hr_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
