"""add_hr_module_tables

Revision ID: ef797612eac4
Revises: c265526a0530
Create Date: 2026-07-07 17:01:41.764324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS hr')
    op.create_table('candidates',
    sa.Column('name', sa.String(length=64), nullable=False, comment='候选人姓名'),
    sa.Column('position', sa.String(length=64), nullable=False, comment='应聘职位名称'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'),
    sa.Column('school', sa.String(length=128), nullable=True, comment='学校名称'),
    sa.Column('education', sa.String(length=16), nullable=True, comment='学历'),
    sa.Column('major', sa.String(length=64), nullable=True, comment='专业'),
    sa.Column('match_report', sa.Text(), nullable=True, comment='候选人匹配度报告'),
    sa.Column('recommendation_level', sa.String(length=16), nullable=True, comment='推荐等级'),
    sa.Column('resume_attachments', sa.JSON(), nullable=True, comment='简历附件元数据'),
    sa.Column('resume_storage_path', sa.String(length=256), nullable=True, comment='本地简历存储路径'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('feishu_sync_status', sa.String(length=16), nullable=True, comment='飞书同步状态: synced/failed'),
    sa.Column('feishu_sync_error', sa.Text(), nullable=True, comment='飞书同步失败原因'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_candidates_feishu_record_id', 'candidates', ['feishu_record_id'], unique=False, schema='hr')
    op.create_index('ix_candidates_name', 'candidates', ['name'], unique=False, schema='hr')
    op.create_index('ix_candidates_position', 'candidates', ['position'], unique=False, schema='hr')
    op.create_index('ix_candidates_recommendation_level', 'candidates', ['recommendation_level'], unique=False, schema='hr')
    op.create_table('prejob_training_plan_templates',
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('factory', sa.String(length=8), server_default='old', nullable=False, comment='厂区: old=旧厂, new=新厂'),
    sa.Column('items', sa.JSON(), server_default='[]', nullable=False, comment='培训计划条目列表 [{seq, content, deadline, trainer}]'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_prejob_template_dept_factory', 'prejob_training_plan_templates', ['department', 'factory'], unique=True, schema='hr')
    op.create_table('training_sessions',
    sa.Column('factory', sa.String(length=8), server_default='old', nullable=False, comment='厂区: old=旧厂, new=新厂'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='主办部门'),
    sa.Column('training_date', sa.Date(), nullable=False, comment='培训日期'),
    sa.Column('subject', sa.String(length=256), nullable=False, comment='培训主题'),
    sa.Column('training_time_start', sa.String(length=32), nullable=True, comment='培训开始时间'),
    sa.Column('training_time_end', sa.String(length=32), nullable=True, comment='培训结束时间'),
    sa.Column('location', sa.String(length=128), nullable=True, comment='培训地点'),
    sa.Column('trainer', sa.String(length=128), nullable=True, comment='培训师'),
    sa.Column('training_method', sa.String(length=32), nullable=True, comment='培训方式'),
    sa.Column('content', sa.String(length=512), nullable=True, comment='培训内容'),
    sa.Column('trainee_departments', sa.JSON(), nullable=True, comment='受训部门列表'),
    sa.Column('employee_names', sa.JSON(), nullable=True, comment='应出席受训人员姓名列表'),
    sa.Column('employee_numbers', sa.JSON(), nullable=True, comment='应出席受训人员工号列表'),
    sa.Column('issuer_department', sa.String(length=64), nullable=True, comment='落款部门'),
    sa.Column('issue_date', sa.Date(), nullable=True, comment='落款日期'),
    sa.Column('remarks', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False, comment='状态: draft草稿, notified已通知, selecting选择中, confirmed已确认, evaluated已评估, archived已归档'),
    sa.Column('select_task_token', sa.String(length=64), nullable=True, comment='飞书选择任务token（兼容旧单任务）'),
    sa.Column('select_tasks', sa.JSON(), nullable=True, comment='多部门选择任务列表[{department, token, status, employee_names, employee_numbers}]'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_sessions_department', 'training_sessions', ['department'], unique=False, schema='hr')
    op.create_index('ix_training_sessions_status', 'training_sessions', ['status'], unique=False, schema='hr')
    op.create_index('ix_training_sessions_training_date', 'training_sessions', ['training_date'], unique=False, schema='hr')
    op.create_table('training_specialists',
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('employee_number', sa.String(length=32), nullable=False, comment='培训专员工号'),
    sa.Column('employee_name', sa.String(length=64), nullable=False, comment='培训专员姓名'),
    sa.Column('factory', sa.String(length=8), server_default='old', nullable=False, comment='厂区: old=旧厂, new=新厂'),
    sa.Column('feishu_open_id', sa.String(length=128), nullable=True, comment='飞书 user open_id'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_specialists_department_factory', 'training_specialists', ['department', 'factory'], unique=True, schema='hr')
    op.create_table('training_teams',
    sa.Column('name', sa.String(length=128), nullable=False, comment='班组名称'),
    sa.Column('factory', sa.String(length=8), server_default='old', nullable=False, comment='厂区: old=旧厂, new=新厂'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='所属部门'),
    sa.Column('specialist_employee_number', sa.String(length=32), nullable=False, comment='培训专员工号'),
    sa.Column('specialist_name', sa.String(length=64), nullable=False, comment='培训专员姓名'),
    sa.Column('employee_names', sa.JSON(), nullable=True, comment='受训人员姓名列表'),
    sa.Column('employee_numbers', sa.JSON(), nullable=True, comment='受训人员工号列表'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.drop_index(op.f('ix_trainers_department'), table_name='trainers', schema='hr')
    op.drop_index(op.f('ix_trainers_name'), table_name='trainers', schema='hr')
    op.drop_table('trainers', schema='hr')
    op.drop_index(op.f('ix_sop_catalog_category'), table_name='sop_catalog', schema='hr')
    op.drop_index(op.f('ix_sop_catalog_department'), table_name='sop_catalog', schema='hr')
    op.drop_table('sop_catalog', schema='hr')
    op.add_column('departments', sa.Column('is_production', sa.Boolean(), server_default='false', nullable=False, comment='是否生产部门'), schema='hr')
    op.add_column('departments', sa.Column('production_start_time', sa.String(length=8), nullable=True, comment='生产班次开始时间(HH:MM)'), schema='hr')
    op.add_column('departments', sa.Column('production_end_time', sa.String(length=8), nullable=True, comment='生产班次结束时间(HH:MM)'), schema='hr')
    op.add_column('employees', sa.Column('position_level', sa.String(length=16), nullable=True, comment='职位级别(自动判定): 普通员工/工程师级/主管级'), schema='hr')
    op.drop_column('employees', 'concurrent_departments', schema='hr')
    op.drop_column('employees', 'sort_order', schema='hr')
    op.add_column('training_ledger_pages', sa.Column('ledger_type', sa.String(length=16), server_default='event', nullable=False, comment='台账类型: event=事件台账, sop=SOP培训台账'), schema='hr')
    op.drop_index(op.f('ix_training_ledger_pages_employee_number'), table_name='training_ledger_pages', schema='hr')
    op.create_index('ix_training_ledger_pages_employee_type', 'training_ledger_pages', ['employee_number', 'ledger_type'], unique=True, schema='hr')
    op.add_column('training_ledgers', sa.Column('ledger_type', sa.String(length=16), server_default='event', nullable=False, comment='台账类型: event=事件台账, sop=SOP培训台账'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_ledgers', 'ledger_type', schema='hr')
    op.drop_index('ix_training_ledger_pages_employee_type', table_name='training_ledger_pages', schema='hr')
    op.create_index(op.f('ix_training_ledger_pages_employee_number'), 'training_ledger_pages', ['employee_number'], unique=True, schema='hr')
    op.drop_column('training_ledger_pages', 'ledger_type', schema='hr')
    op.add_column('employees', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True, comment='Excel行序号'), schema='hr')
    op.add_column('employees', sa.Column('concurrent_departments', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='兼任部门'), schema='hr')
    op.drop_column('employees', 'position_level', schema='hr')
    op.drop_column('departments', 'production_end_time', schema='hr')
    op.drop_column('departments', 'production_start_time', schema='hr')
    op.drop_column('departments', 'is_production', schema='hr')
    op.create_table('sop_catalog',
    sa.Column('file_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sop_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('sop_catalog_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('sop_catalog_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sop_catalog_pkey')),
    schema='hr'
    )
    op.create_index(op.f('ix_sop_catalog_department'), 'sop_catalog', ['department'], unique=False, schema='hr')
    op.create_index(op.f('ix_sop_catalog_category'), 'sop_catalog', ['category'], unique=False, schema='hr')
    op.create_table('trainers',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('trainable_departments', sa.TEXT(), autoincrement=False, nullable=True, comment='可培训部门'),
    sa.Column('qualification_scope', sa.TEXT(), autoincrement=False, nullable=True, comment='资格范围'),
    sa.Column('certification_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('confirmation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('confirmation_reminder', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_primary_trainer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('trainers_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('trainers_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trainers_pkey')),
    schema='hr'
    )
    op.create_index(op.f('ix_trainers_name'), 'trainers', ['name'], unique=False, schema='hr')
    op.create_index(op.f('ix_trainers_department'), 'trainers', ['department'], unique=False, schema='hr')
    op.drop_table('training_teams', schema='hr')
    op.drop_index('ix_training_specialists_department_factory', table_name='training_specialists', schema='hr')
    op.drop_table('training_specialists', schema='hr')
    op.drop_index('ix_training_sessions_training_date', table_name='training_sessions', schema='hr')
    op.drop_index('ix_training_sessions_status', table_name='training_sessions', schema='hr')
    op.drop_index('ix_training_sessions_department', table_name='training_sessions', schema='hr')
    op.drop_table('training_sessions', schema='hr')
    op.drop_index('ix_prejob_template_dept_factory', table_name='prejob_training_plan_templates', schema='hr')
    op.drop_table('prejob_training_plan_templates', schema='hr')
    op.drop_index('ix_candidates_recommendation_level', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_position', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_name', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_feishu_record_id', table_name='candidates', schema='hr')
    op.drop_table('candidates', schema='hr')
    # ### end Alembic commands ###
