"""add_safety_module_tables

Revision ID: 0021_add_safety_module_tables
Revises: 0020_add_production_module_tables
Create Date: 2026-07-07 17:02:00.647085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021_add_safety_module_tables'
down_revision: Union[str, None] = '0020_add_production_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS safety')
    op.add_column('hazard_reports', sa.Column('defect_substance', sa.String(length=32), nullable=True, comment='缺陷实质评估: substantive / procedural / uncertain'), schema='safety')
    op.add_column('hazard_reports', sa.Column('defect_substance_reasoning', sa.Text(), nullable=True, comment='缺陷实质评估理由'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hazard_reports', 'defect_substance_reasoning', schema='safety')
    op.drop_column('hazard_reports', 'defect_substance', schema='safety')
    # ### end Alembic commands ###
