"""add_identity_module_tables

Revision ID: 0022_add_identity_module_tables
Revises: 0021_add_safety_module_tables
Create Date: 2026-07-07 17:04:36.920337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0022_add_identity_module_tables'
down_revision: Union[str, None] = '0021_add_safety_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS identity')
    op.create_foreign_key(None, 'feishu_card_actions', 'users', ['updated_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.create_foreign_key(None, 'feishu_card_actions', 'users', ['created_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.alter_column('feishu_configs', 'config_name',
               existing_type=sa.VARCHAR(length=128),
               comment='配置名称，仅用于 Livzon 助手',
               existing_nullable=False,
               schema='identity')
    op.alter_column('feishu_configs', 'app_id',
               existing_type=sa.VARCHAR(length=128),
               comment='飞书自建应用 App ID',
               existing_nullable=False,
               schema='identity')
    op.alter_column('feishu_configs', 'encrypted_app_secret',
               existing_type=sa.VARCHAR(length=1024),
               comment='加密后的飞书自建应用 App Secret',
               existing_nullable=False,
               schema='identity')
    op.alter_column('feishu_configs', 'sync_root_department_id',
               existing_type=sa.VARCHAR(length=128),
               comment='组织架构同步根部门 ID',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'sync_member_department_id',
               existing_type=sa.VARCHAR(length=128),
               comment='成员同步部门 ID',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='identity')
    op.alter_column('feishu_configs', 'last_sync_status',
               existing_type=sa.VARCHAR(length=32),
               comment='最近同步状态',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_sync_message',
               existing_type=sa.TEXT(),
               comment='最近同步信息',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近同步时间',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_status',
               existing_type=sa.VARCHAR(length=32),
               comment='最近诊断状态',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_message',
               existing_type=sa.TEXT(),
               comment='最近诊断信息',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_result',
               existing_type=sa.TEXT(),
               comment='最近诊断结果 JSON',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnosed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近诊断时间',
               existing_nullable=True,
               schema='identity')
    op.drop_index(op.f('ix_identity_feishu_configs_is_active'), table_name='feishu_configs', schema='identity')
    op.create_foreign_key(None, 'feishu_configs', 'users', ['updated_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.create_foreign_key(None, 'feishu_configs', 'users', ['created_by'], ['id'], source_schema='identity', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feishu_configs', schema='identity', type_='foreignkey')
    op.drop_constraint(None, 'feishu_configs', schema='identity', type_='foreignkey')
    op.create_index(op.f('ix_identity_feishu_configs_is_active'), 'feishu_configs', ['is_active'], unique=False, schema='identity')
    op.alter_column('feishu_configs', 'last_diagnosed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最近诊断时间',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_result',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='最近诊断结果 JSON',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='最近诊断信息',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_diagnostic_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='最近诊断状态',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最近同步时间',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_sync_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='最近同步信息',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'last_sync_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='最近同步状态',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='identity')
    op.alter_column('feishu_configs', 'sync_member_department_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='成员同步部门 ID',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'sync_root_department_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='组织架构同步根部门 ID',
               existing_nullable=True,
               schema='identity')
    op.alter_column('feishu_configs', 'encrypted_app_secret',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='加密后的飞书自建应用 App Secret',
               existing_nullable=False,
               schema='identity')
    op.alter_column('feishu_configs', 'app_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='飞书自建应用 App ID',
               existing_nullable=False,
               schema='identity')
    op.alter_column('feishu_configs', 'config_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='配置名称，仅用于 Livzon 助手',
               existing_nullable=False,
               schema='identity')
    op.drop_constraint(None, 'feishu_card_actions', schema='identity', type_='foreignkey')
    op.drop_constraint(None, 'feishu_card_actions', schema='identity', type_='foreignkey')
    # ### end Alembic commands ###
