"""add_procurement_module_tables

Revision ID: 0023_add_procurement_module_tables
Revises: 0022_add_identity_module_tables
Create Date: 2026-07-07 17:04:58.180846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0023_add_procurement_module_tables'
down_revision: Union[str, None] = '0022_add_identity_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS procurement')
    op.create_foreign_key(None, 'contract_records', 'users', ['created_by'], ['id'], source_schema='procurement', referent_schema='identity')
    op.create_foreign_key(None, 'contract_records', 'users', ['updated_by'], ['id'], source_schema='procurement', referent_schema='identity')
    op.create_foreign_key(None, 'suppliers', 'users', ['updated_by'], ['id'], source_schema='procurement', referent_schema='identity')
    op.create_foreign_key(None, 'suppliers', 'users', ['created_by'], ['id'], source_schema='procurement', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', schema='procurement', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', schema='procurement', type_='foreignkey')
    op.drop_constraint(None, 'contract_records', schema='procurement', type_='foreignkey')
    op.drop_constraint(None, 'contract_records', schema='procurement', type_='foreignkey')
    # ### end Alembic commands ###
