"""add quality module missing tables

Revision ID: b725dd3dcfd6
Revises: 17cff8dc643f
Create Date: 2026-07-09 10:56:13.769497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0025'
down_revision: Union[str, None] = '0024_add_instrument_calibration_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS quality')
    op.create_table('inspection_tables',
    sa.Column('table_name', sa.String(length=255), nullable=False, comment='数据表名称'),
    sa.Column('table_description', sa.Text(), nullable=True, comment='数据表描述'),
    sa.Column('columns_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False, comment='列配置'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('template_path', sa.String(length=500), nullable=True, comment='Word模板路径'),
    sa.Column('template_name', sa.String(length=255), nullable=True, comment='Word模板名称'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name'),
    schema='quality'
    )
    op.create_index('idx_inspection_table_active', 'inspection_tables', ['is_active'], unique=False, schema='quality')
    op.create_index('idx_inspection_table_name', 'inspection_tables', ['table_name'], unique=False, schema='quality')
    op.create_table('report_templates',
    sa.Column('template_name', sa.String(length=255), nullable=False, comment='模板名称'),
    sa.Column('template_file_url', sa.String(length=500), nullable=False, comment='模板文件存储路径'),
    sa.Column('template_description', sa.Text(), nullable=True, comment='模板描述说明'),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='静态字段映射配置'),
    sa.Column('table_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='动态表格字段定义'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index('idx_template_active', 'report_templates', ['is_active'], unique=False, schema='quality')
    op.create_index('idx_template_name', 'report_templates', ['template_name'], unique=True, schema='quality')
    op.create_table('inspection_table_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False, comment='关联数据表ID'),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='行数据'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['quality.inspection_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index('idx_table_row_table', 'inspection_table_rows', ['table_id'], unique=False, schema='quality')
    op.create_table('material_reports',
    sa.Column('report_no', sa.String(length=64), nullable=False, comment='报告单编号'),
    sa.Column('template_id', sa.UUID(), nullable=True, comment='关联模板ID'),
    sa.Column('report_title', sa.String(length=255), nullable=False, comment='报告单标题'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报告日期'),
    sa.Column('static_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='静态字段数据'),
    sa.Column('status', sa.Enum('draft', 'completed', 'approved', 'archived', name='report_status_enum'), nullable=False, comment='状态'),
    sa.Column('generated_file_url', sa.String(length=500), nullable=True, comment='生成文件路径'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['quality.report_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no'),
    sa.UniqueConstraint('report_no', name='uq_report_no'),
    schema='quality'
    )
    op.create_index('idx_report_date', 'material_reports', ['report_date'], unique=False, schema='quality')
    op.create_index('idx_report_status', 'material_reports', ['status'], unique=False, schema='quality')
    op.create_index('idx_report_template', 'material_reports', ['template_id'], unique=False, schema='quality')
    op.create_table('material_report_items',
    sa.Column('report_id', sa.UUID(), nullable=False, comment='关联报告单ID'),
    sa.Column('row_index', sa.Integer(), nullable=False, comment='行序号'),
    sa.Column('field_key', sa.String(length=100), nullable=False, comment='字段标识'),
    sa.Column('field_value', sa.Text(), nullable=True, comment='字段值'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['quality.material_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'row_index', 'field_key', name='uq_item_composite'),
    schema='quality'
    )
    op.create_index('idx_item_report', 'material_report_items', ['report_id'], unique=False, schema='quality')
    op.create_index('idx_item_row', 'material_report_items', ['row_index'], unique=False, schema='quality')
    op.create_table('report_images',
    sa.Column('report_id', sa.UUID(), nullable=False, comment='关联报告单ID'),
    sa.Column('row_index', sa.Integer(), nullable=True, comment='关联行序号'),
    sa.Column('field_key', sa.String(length=100), nullable=True, comment='对应字段'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='图片路径'),
    sa.Column('ai_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI识别结果'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['quality.material_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index('idx_image_field', 'report_images', ['field_key'], unique=False, schema='quality')
    op.create_index('idx_image_report', 'report_images', ['report_id'], unique=False, schema='quality')
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:54:28.350503+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.drop_index('idx_image_report', table_name='report_images', schema='quality')
    op.drop_index('idx_image_field', table_name='report_images', schema='quality')
    op.drop_table('report_images', schema='quality')
    op.drop_index('idx_item_row', table_name='material_report_items', schema='quality')
    op.drop_index('idx_item_report', table_name='material_report_items', schema='quality')
    op.drop_table('material_report_items', schema='quality')
    op.drop_index('idx_report_template', table_name='material_reports', schema='quality')
    op.drop_index('idx_report_status', table_name='material_reports', schema='quality')
    op.drop_index('idx_report_date', table_name='material_reports', schema='quality')
    op.drop_table('material_reports', schema='quality')
    op.drop_index('idx_table_row_table', table_name='inspection_table_rows', schema='quality')
    op.drop_table('inspection_table_rows', schema='quality')
    op.drop_index('idx_template_name', table_name='report_templates', schema='quality')
    op.drop_index('idx_template_active', table_name='report_templates', schema='quality')
    op.drop_table('report_templates', schema='quality')
    op.drop_index('idx_inspection_table_name', table_name='inspection_tables', schema='quality')
    op.drop_index('idx_inspection_table_active', table_name='inspection_tables', schema='quality')
    op.drop_table('inspection_tables', schema='quality')
    # ### end Alembic commands ###
