"""add sop ai tables

Revision ID: 8d4468aed210
Revises: 0025
Create Date: 2026-07-09 12:13:49.254444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0026'
down_revision: Union[str, None] = '0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS quality')
    op.create_table('sop_ai_check_main',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('file_code', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=False),
    sa.Column('risk_high', sa.Integer(), nullable=False),
    sa.Column('risk_medium', sa.Integer(), nullable=False),
    sa.Column('risk_low', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index('ix_sop_ai_check_main_created_at', 'sop_ai_check_main', ['created_at'], unique=False, schema='quality')
    op.create_index('ix_sop_ai_check_main_file_code', 'sop_ai_check_main', ['file_code'], unique=False, schema='quality')
    op.create_index('ix_sop_ai_check_main_status', 'sop_ai_check_main', ['status'], unique=False, schema='quality')
    op.create_table('sop_ai_check_problem',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('main_id', sa.String(length=36), nullable=False),
    sa.Column('problem_type', sa.Enum('DUPLICATE', 'CONFLICT', 'COMPLIANCE', 'FORMAT', 'CONTENT', name='problemtype'), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('handle_status', sa.Enum('PENDING', 'CONFIRMED', 'IGNORED', 'FIXED', name='handlestatus'), nullable=False),
    sa.Column('ignore_reason', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['main_id'], ['quality.sop_ai_check_main.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index('ix_sop_ai_check_problem_handle_status', 'sop_ai_check_problem', ['handle_status'], unique=False, schema='quality')
    op.create_index('ix_sop_ai_check_problem_main_id', 'sop_ai_check_problem', ['main_id'], unique=False, schema='quality')
    op.create_index('ix_sop_ai_check_problem_risk_level', 'sop_ai_check_problem', ['risk_level'], unique=False, schema='quality')
    op.create_table('sop_ai_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    schema='quality'
    )
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False,
               schema='quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stability_studies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_studies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_sample_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('stability_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sampling_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('sample_retention_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('iqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('ipqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_inspection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.alter_column('fqc_approval_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-07-09 10:59:12.33786+00'::timestamp with time zone"),
               existing_nullable=False,
               schema='quality')
    op.drop_table('sop_ai_config', schema='quality')
    op.drop_index('ix_sop_ai_check_problem_risk_level', table_name='sop_ai_check_problem', schema='quality')
    op.drop_index('ix_sop_ai_check_problem_main_id', table_name='sop_ai_check_problem', schema='quality')
    op.drop_index('ix_sop_ai_check_problem_handle_status', table_name='sop_ai_check_problem', schema='quality')
    op.drop_table('sop_ai_check_problem', schema='quality')
    op.drop_index('ix_sop_ai_check_main_status', table_name='sop_ai_check_main', schema='quality')
    op.drop_index('ix_sop_ai_check_main_file_code', table_name='sop_ai_check_main', schema='quality')
    op.drop_index('ix_sop_ai_check_main_created_at', table_name='sop_ai_check_main', schema='quality')
    op.drop_table('sop_ai_check_main', schema='quality')
    # ### end Alembic commands ###
