"""add qms ai tables

Revision ID: 4d47f5fcff05
Revises: 0026
Create Date: 2026-07-09 12:32:22.408587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0027_add_qms_ai_tables'
down_revision: Union[str, None] = '0026_add_sop_ai_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS qms')
    op.create_table('qms_ai_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    schema='qms'
    )
    op.create_table('qms_ai_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_no', sa.String(length=100), nullable=True, comment='关联单据编号'),
    sa.Column('operate_type', sa.String(length=50), nullable=False, comment='操作类型：如 试剂领用辅助、试剂报废辅助'),
    sa.Column('operator', sa.String(length=100), nullable=False, comment='操作人账号'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='系统提示词'),
    sa.Column('user_input', sa.Text(), nullable=False, comment='用户输入内容'),
    sa.Column('ai_response', sa.Text(), nullable=True, comment='AI 返回内容'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='使用的 token 数量'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='响应耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qms'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qms_ai_log', schema='qms')
    op.drop_table('qms_ai_config', schema='qms')
    # ### end Alembic commands ###
