"""add regulatory tracker tables

Revision ID: 91e48d30b8c7
Revises: 0027
Create Date: 2026-07-10 00:49:38.145049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028'
down_revision: Union[str, None] = '0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS regulatory_tracker')
    op.create_foreign_key(None, 'data_channels', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_channels', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_sources', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_sources', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'regulatory_documents', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'regulatory_documents', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_job_pages', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_job_pages', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_jobs', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_jobs', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_job_pages', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_job_pages', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_sources', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_sources', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_channels', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_channels', schema='regulatory_tracker', type_='foreignkey')
    # ### end Alembic commands ###
