"""add_agent_tables

Revision ID: 0029_add_agent_tables
Revises: 0028_safety_feishu_record_id_unique
Create Date: 2026-07-12 11:33:33.282156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0029_add_agent_tables'
down_revision: Union[str, None] = '0028_safety_feishu_record_id_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS core')
    op.execute('CREATE SCHEMA IF NOT EXISTS hr')
    op.execute('CREATE SCHEMA IF NOT EXISTS quality')
    op.create_table('agent_confirmations',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=32), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent write operation confirmations'
    )
    op.create_index(op.f('ix_core_agent_confirmations_operation'), 'agent_confirmations', ['operation'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_session_id'), 'agent_confirmations', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_user_id'), 'agent_confirmations', ['user_id'], unique=False, schema='core')
    op.create_table('agent_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent conversation messages'
    )
    op.create_index(op.f('ix_core_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False, schema='core')
    op.create_table('agent_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent conversation sessions'
    )
    op.create_index(op.f('ix_core_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False, schema='core')
    op.create_table('agent_skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_core_agent_skills_name'),
    schema='core',
    comment='Agent progressive disclosure skills'
    )
    op.create_index(op.f('ix_core_agent_skills_name'), 'agent_skills', ['name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_skills_status'), 'agent_skills', ['status'], unique=False, schema='core')
    op.create_table('agent_tool_calls',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='started', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent tool execution audit'
    )
    op.create_index(op.f('ix_core_agent_tool_calls_operation'), 'agent_tool_calls', ['operation'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_tool_calls_session_id'), 'agent_tool_calls', ['session_id'], unique=False, schema='core')
    op.create_table('agent_workflow_runs',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('steps_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('step_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent workflow run state'
    )
    op.create_index(op.f('ix_core_agent_workflow_runs_session_id'), 'agent_workflow_runs', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_status'), 'agent_workflow_runs', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_user_id'), 'agent_workflow_runs', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_workflow_id'), 'agent_workflow_runs', ['workflow_id'], unique=False, schema='core')
    op.create_table('agent_workflows',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='enabled', nullable=False),
    sa.Column('trigger_phrases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('source_skill', sa.String(length=120), nullable=True),
    sa.Column('source_request', sa.Text(), nullable=True),
    sa.Column('last_run_id', sa.Uuid(), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent user workflow definitions'
    )
    op.create_index(op.f('ix_core_agent_workflows_session_id'), 'agent_workflows', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_status'), 'agent_workflows', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_user_id'), 'agent_workflows', ['user_id'], unique=False, schema='core')
    op.alter_column('candidates', 'resume_attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='简历附件元数据',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_reason',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='离职原因（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_reason_2',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='离职原因2（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_remarks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='离职备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'qualifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='职称／职业资格（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'remarks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('onboarding_records', 'remarks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('prejob_training_plan_templates', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='培训计划条目列表 [{seq, content, deadline, trainer}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='hr')
    op.alter_column('training_sessions', 'trainee_departments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='受训部门列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'employee_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='应出席受训人员姓名列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'employee_numbers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='应出席受训人员工号列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'select_tasks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='多部门选择任务列表[{department, token, status, employee_names, employee_numbers}]',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_teams', 'employee_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='受训人员姓名列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_teams', 'employee_numbers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='受训人员工号列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('calibration_reminder_config', 'receive_id_type',
               existing_type=sa.VARCHAR(length=20),
               comment='接收类型: chat_id/user_id',
               existing_comment='接收类型',
               existing_nullable=False,
               existing_server_default=sa.text("'chat_id'::character varying"),
               schema='quality')
    op.create_foreign_key(None, 'calibration_reminder_config', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'calibration_reminder_config', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_approvals', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_approvals', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.add_column('instrument_calibration_records', sa.Column('rule_id', sa.UUID(), nullable=True, comment='关联校准规则ID'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('calibration_end_date', sa.DateTime(timezone=True), nullable=True, comment='校准完成日期'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('calibration_agency', sa.String(length=255), nullable=True, comment='校准机构'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('calibrator_id', sa.UUID(), nullable=True, comment='校准人员ID'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('calibrator_name', sa.String(length=100), nullable=True, comment='校准人员'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('certificate_url', sa.String(length=512), nullable=True, comment='校准证书附件URL'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('result_reason', sa.Text(), nullable=True, comment='结论说明'), schema='quality')
    op.alter_column('instrument_calibration_records', 'instrument_id',
               existing_type=sa.UUID(),
               comment='关联仪器ID',
               existing_comment='仪器ID',
               existing_nullable=False,
               schema='quality')
    op.alter_column('instrument_calibration_records', 'calibration_no',
               existing_type=sa.VARCHAR(length=64),
               comment='校准单据编号',
               existing_comment='校准记录编号',
               existing_nullable=False,
               schema='quality')
    op.alter_column('instrument_calibration_records', 'certificate_no',
               existing_type=sa.VARCHAR(length=128),
               comment='校准证书编号',
               existing_comment='证书编号',
               existing_nullable=True,
               schema='quality')
    op.drop_index(op.f('idx_calibration_no'), table_name='instrument_calibration_records', schema='quality')
    op.create_index('idx_calibration_no', 'instrument_calibration_records', ['calibration_no'], unique=True, schema='quality')
    op.create_unique_constraint(None, 'instrument_calibration_records', ['calibration_no'], schema='quality')
    op.create_foreign_key(None, 'instrument_calibration_records', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_records', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_records', 'instrument_calibrations', ['instrument_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.drop_column('instrument_calibration_records', 'calibration_institution', schema='quality')
    op.drop_column('instrument_calibration_records', 'result_description', schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('calibration_cycle', sa.Integer(), nullable=True, comment='校准周期'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('calibration_unit', sa.String(length=32), nullable=True, comment='周期单位'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('calibration_agency', sa.String(length=255), nullable=True, comment='校准机构名称'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('agency_contact', sa.String(length=255), nullable=True, comment='机构联系方式'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('internal_calibrator_id', sa.UUID(), nullable=True, comment='内校人员ID'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('internal_calibrator_name', sa.String(length=100), nullable=True, comment='内校人员'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('warning_days', sa.Integer(), server_default='7', nullable=True, comment='提前预警天数'), schema='quality')
    op.alter_column('instrument_calibration_rules', 'instrument_id',
               existing_type=sa.UUID(),
               comment='关联仪器ID',
               existing_comment='仪器ID',
               existing_nullable=False,
               schema='quality')
    op.alter_column('instrument_calibration_rules', 'last_calibration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近校准日期',
               existing_comment='上次校准日期',
               existing_nullable=True,
               schema='quality')
    op.create_foreign_key(None, 'instrument_calibration_rules', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_rules', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibration_rules', 'instrument_calibrations', ['instrument_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.drop_column('instrument_calibration_rules', 'remark', schema='quality')
    op.drop_column('instrument_calibration_rules', 'rule_name', schema='quality')
    op.drop_column('instrument_calibration_rules', 'cycle_unit', schema='quality')
    op.drop_column('instrument_calibration_rules', 'cycle_value', schema='quality')
    op.drop_index(op.f('idx_instrument_no'), table_name='instrument_calibrations', schema='quality')
    op.create_index('idx_instrument_no', 'instrument_calibrations', ['instrument_no'], unique=True, schema='quality')
    op.create_foreign_key(None, 'instrument_calibrations', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'instrument_calibrations', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrument_calibrations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibrations', schema='quality', type_='foreignkey')
    op.drop_index('idx_instrument_no', table_name='instrument_calibrations', schema='quality')
    op.create_index(op.f('idx_instrument_no'), 'instrument_calibrations', ['instrument_no'], unique=False, schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('cycle_value', sa.INTEGER(), autoincrement=False, nullable=False, comment='校准周期值'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('cycle_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='校准周期单位'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('rule_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='规则名称'), schema='quality')
    op.add_column('instrument_calibration_rules', sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'), schema='quality')
    op.drop_constraint(None, 'instrument_calibration_rules', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_rules', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_rules', schema='quality', type_='foreignkey')
    op.alter_column('instrument_calibration_rules', 'last_calibration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='上次校准日期',
               existing_comment='最近校准日期',
               existing_nullable=True,
               schema='quality')
    op.alter_column('instrument_calibration_rules', 'instrument_id',
               existing_type=sa.UUID(),
               comment='仪器ID',
               existing_comment='关联仪器ID',
               existing_nullable=False,
               schema='quality')
    op.drop_column('instrument_calibration_rules', 'warning_days', schema='quality')
    op.drop_column('instrument_calibration_rules', 'internal_calibrator_name', schema='quality')
    op.drop_column('instrument_calibration_rules', 'internal_calibrator_id', schema='quality')
    op.drop_column('instrument_calibration_rules', 'agency_contact', schema='quality')
    op.drop_column('instrument_calibration_rules', 'calibration_agency', schema='quality')
    op.drop_column('instrument_calibration_rules', 'calibration_unit', schema='quality')
    op.drop_column('instrument_calibration_rules', 'calibration_cycle', schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('result_description', sa.TEXT(), autoincrement=False, nullable=True, comment='结论说明'), schema='quality')
    op.add_column('instrument_calibration_records', sa.Column('calibration_institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='校准机构'), schema='quality')
    op.drop_constraint(None, 'instrument_calibration_records', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_records', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_records', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_records', schema='quality', type_='unique')
    op.drop_index('idx_calibration_no', table_name='instrument_calibration_records', schema='quality')
    op.create_index(op.f('idx_calibration_no'), 'instrument_calibration_records', ['calibration_no'], unique=False, schema='quality')
    op.alter_column('instrument_calibration_records', 'certificate_no',
               existing_type=sa.VARCHAR(length=128),
               comment='证书编号',
               existing_comment='校准证书编号',
               existing_nullable=True,
               schema='quality')
    op.alter_column('instrument_calibration_records', 'calibration_no',
               existing_type=sa.VARCHAR(length=64),
               comment='校准记录编号',
               existing_comment='校准单据编号',
               existing_nullable=False,
               schema='quality')
    op.alter_column('instrument_calibration_records', 'instrument_id',
               existing_type=sa.UUID(),
               comment='仪器ID',
               existing_comment='关联仪器ID',
               existing_nullable=False,
               schema='quality')
    op.drop_column('instrument_calibration_records', 'result_reason', schema='quality')
    op.drop_column('instrument_calibration_records', 'certificate_url', schema='quality')
    op.drop_column('instrument_calibration_records', 'calibrator_name', schema='quality')
    op.drop_column('instrument_calibration_records', 'calibrator_id', schema='quality')
    op.drop_column('instrument_calibration_records', 'calibration_agency', schema='quality')
    op.drop_column('instrument_calibration_records', 'calibration_end_date', schema='quality')
    op.drop_column('instrument_calibration_records', 'rule_id', schema='quality')
    op.drop_constraint(None, 'instrument_calibration_approvals', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'instrument_calibration_approvals', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'calibration_reminder_config', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'calibration_reminder_config', schema='quality', type_='foreignkey')
    op.alter_column('calibration_reminder_config', 'receive_id_type',
               existing_type=sa.VARCHAR(length=20),
               comment='接收类型',
               existing_comment='接收类型: chat_id/user_id',
               existing_nullable=False,
               existing_server_default=sa.text("'chat_id'::character varying"),
               schema='quality')
    op.alter_column('training_teams', 'employee_numbers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='受训人员工号列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_teams', 'employee_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='受训人员姓名列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'select_tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='多部门选择任务列表[{department, token, status, employee_names, employee_numbers}]',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'employee_numbers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='应出席受训人员工号列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'employee_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='应出席受训人员姓名列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('training_sessions', 'trainee_departments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='受训部门列表',
               existing_nullable=True,
               schema='hr')
    op.alter_column('prejob_training_plan_templates', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='培训计划条目列表 [{seq, content, deadline, trainer}]',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               schema='hr')
    op.alter_column('onboarding_records', 'remarks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'remarks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'qualifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='职称／职业资格（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_remarks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='离职备注（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_reason_2',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='离职原因2（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_reason',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='离职原因（多选）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('candidates', 'resume_attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='简历附件元数据',
               existing_nullable=True,
               schema='hr')
    op.drop_index(op.f('ix_core_agent_workflows_user_id'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_status'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_session_id'), table_name='agent_workflows', schema='core')
    op.drop_table('agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_workflow_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_user_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_status'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_session_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_table('agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_tool_calls_session_id'), table_name='agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_tool_calls_operation'), table_name='agent_tool_calls', schema='core')
    op.drop_table('agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_status'), table_name='agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_name'), table_name='agent_skills', schema='core')
    op.drop_table('agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_sessions_user_id'), table_name='agent_sessions', schema='core')
    op.drop_table('agent_sessions', schema='core')
    op.drop_index(op.f('ix_core_agent_messages_session_id'), table_name='agent_messages', schema='core')
    op.drop_table('agent_messages', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_user_id'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_session_id'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_operation'), table_name='agent_confirmations', schema='core')
    op.drop_table('agent_confirmations', schema='core')
    # ### end Alembic commands ###
