"""add_agent_core_tables

Revision ID: 0029_add_agent_core_tables
Revises: 0028_safety_feishu_record_id_unique
Create Date: 2026-07-12 11:33:33.282156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0029_add_agent_core_tables'
down_revision: Union[str, None] = '0028_safety_feishu_record_id_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS core')
    op.create_table('agent_confirmations',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=32), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent write operation confirmations'
    )
    op.create_index(op.f('ix_core_agent_confirmations_operation'), 'agent_confirmations', ['operation'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_session_id'), 'agent_confirmations', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_confirmations_user_id'), 'agent_confirmations', ['user_id'], unique=False, schema='core')
    op.create_table('agent_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent conversation messages'
    )
    op.create_index(op.f('ix_core_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False, schema='core')
    op.create_table('agent_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent conversation sessions'
    )
    op.create_index(op.f('ix_core_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False, schema='core')
    op.create_table('agent_skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_core_agent_skills_name'),
    schema='core',
    comment='Agent progressive disclosure skills'
    )
    op.create_index(op.f('ix_core_agent_skills_name'), 'agent_skills', ['name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_skills_status'), 'agent_skills', ['status'], unique=False, schema='core')
    op.create_table('agent_tool_calls',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='started', nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent tool execution audit'
    )
    op.create_index(op.f('ix_core_agent_tool_calls_operation'), 'agent_tool_calls', ['operation'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_tool_calls_session_id'), 'agent_tool_calls', ['session_id'], unique=False, schema='core')
    op.create_table('agent_workflow_runs',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('steps_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('step_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent workflow run state'
    )
    op.create_index(op.f('ix_core_agent_workflow_runs_session_id'), 'agent_workflow_runs', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_status'), 'agent_workflow_runs', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_user_id'), 'agent_workflow_runs', ['user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflow_runs_workflow_id'), 'agent_workflow_runs', ['workflow_id'], unique=False, schema='core')
    op.create_table('agent_workflows',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='enabled', nullable=False),
    sa.Column('trigger_phrases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('source_skill', sa.String(length=120), nullable=True),
    sa.Column('source_request', sa.Text(), nullable=True),
    sa.Column('last_run_id', sa.Uuid(), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core',
    comment='Agent user workflow definitions'
    )
    op.create_index(op.f('ix_core_agent_workflows_session_id'), 'agent_workflows', ['session_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_status'), 'agent_workflows', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_core_agent_workflows_user_id'), 'agent_workflows', ['user_id'], unique=False, schema='core')


def downgrade() -> None:
    op.drop_index(op.f('ix_core_agent_workflows_user_id'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_status'), table_name='agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflows_session_id'), table_name='agent_workflows', schema='core')
    op.drop_table('agent_workflows', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_workflow_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_user_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_status'), table_name='agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_workflow_runs_session_id'), table_name='agent_workflow_runs', schema='core')
    op.drop_table('agent_workflow_runs', schema='core')
    op.drop_index(op.f('ix_core_agent_tool_calls_session_id'), table_name='agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_tool_calls_operation'), table_name='agent_tool_calls', schema='core')
    op.drop_table('agent_tool_calls', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_status'), table_name='agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_skills_name'), table_name='agent_skills', schema='core')
    op.drop_table('agent_skills', schema='core')
    op.drop_index(op.f('ix_core_agent_sessions_user_id'), table_name='agent_sessions', schema='core')
    op.drop_table('agent_sessions', schema='core')
    op.drop_index(op.f('ix_core_agent_messages_session_id'), table_name='agent_messages', schema='core')
    op.drop_table('agent_messages', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_user_id'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_session_id'), table_name='agent_confirmations', schema='core')
    op.drop_index(op.f('ix_core_agent_confirmations_operation'), table_name='agent_confirmations', schema='core')
    op.drop_table('agent_confirmations', schema='core')

