"""add_permission_module_tables

Revision ID: 0d5e0cdfe9a4
Revises: ef797612eac4
Create Date: 2026-07-07 17:01:51.578420
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5e0cdfe9a4'
down_revision: Union[str, None] = 'ef797612eac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
