"""add_safety_module_tables

Revision ID: 39df821ea2f4
Revises: c94acb8b71cb
Create Date: 2026-07-07 17:02:00.647085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39df821ea2f4'
down_revision: Union[str, None] = 'c94acb8b71cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS safety')
    op.add_column('hazard_reports', sa.Column('defect_substance', sa.String(length=32), nullable=True, comment='缺陷实质评估: substantive / procedural / uncertain'), schema='safety')
    op.add_column('hazard_reports', sa.Column('defect_substance_reasoning', sa.Text(), nullable=True, comment='缺陷实质评估理由'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hazard_reports', 'defect_substance_reasoning', schema='safety')
    op.drop_column('hazard_reports', 'defect_substance', schema='safety')
    # ### end Alembic commands ###
