"""0045_energy_add_workshop_and_steam

Revision ID: 49684887bf7e
Revises: 74a464371488
Create Date: 2026-07-15 19:25:58.830586
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49684887bf7e'
down_revision: Union[str, None] = '74a464371488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS energy')
    op.create_table('energy_workshops',
    sa.Column('code', sa.String(length=50), nullable=False, comment='车间编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='车间名称'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类: workshop/position/support/utility'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父级车间ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['energy.energy_workshops.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_energy_workshop_code'),
    schema='energy'
    )
    op.create_table('energy_monthly_records',
    sa.Column('workshop_id', sa.UUID(), nullable=False, comment='车间ID'),
    sa.Column('energy_type', sa.String(length=20), nullable=False, comment='能源类型'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('date_range_end', sa.Date(), nullable=True, comment='日期范围结束（多日汇总时使用）'),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False, comment='能耗值'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='数据来源'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("energy_type IN ('electricity', 'water', 'steam', 'natural_gas')", name='ck_energy_monthly_record_energy_type'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['energy.energy_workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'energy_type', 'record_date', name='uq_energy_monthly_record'),
    schema='energy'
    )
    op.alter_column('energy_collect_logs', 'success_count',
               existing_type=sa.INTEGER(),
               comment='成功采集数',
               existing_comment='成功条数',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_device_configs', 'energy_type',
               existing_type=sa.VARCHAR(length=20),
               comment='能源类型: electricity/water/steam',
               existing_comment='能源类型: electricity/water/gas',
               existing_nullable=False,
               schema='energy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_device_configs', 'energy_type',
               existing_type=sa.VARCHAR(length=20),
               comment='能源类型: electricity/water/gas',
               existing_comment='能源类型: electricity/water/steam',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_collect_logs', 'success_count',
               existing_type=sa.INTEGER(),
               comment='成功条数',
               existing_comment='成功采集数',
               existing_nullable=False,
               schema='energy')
    op.drop_table('energy_monthly_records', schema='energy')
    op.drop_table('energy_workshops', schema='energy')
    # ### end Alembic commands ###
