"""add_reagent_quality_table

Revision ID: 0034_add_reagent_quality_table
Revises: 0033_fix_remaining_model_changes
Create Date: 2026-07-14 03:16:34.189421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0034_add_reagent_quality_table'
down_revision: Union[str, None] = '0033_fix_remaining_model_changes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS qms')
    op.create_table('qms_reagent_quality',
    sa.Column('reagent_label_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reagent_name', sa.String(length=200), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('lot_no', sa.String(length=100), nullable=False),
    sa.Column('incoming_lot_no', sa.String(length=100), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('reagent_no', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qms'
    )
    op.create_index('idx_reagent_quality_lot_no', 'qms_reagent_quality', ['lot_no'], unique=False, schema='qms')
    op.create_index('idx_reagent_quality_status', 'qms_reagent_quality', ['status'], unique=False, schema='qms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reagent_quality_status', table_name='qms_reagent_quality', schema='qms')
    op.drop_index('idx_reagent_quality_lot_no', table_name='qms_reagent_quality', schema='qms')
    op.drop_table('qms_reagent_quality', schema='qms')
    # ### end Alembic commands ###
