"""Make rule_id nullable in energy_alert_records

Revision ID: 0049_make_rule_id_nullable_in_energy_alert
Revises: 0046_qms_deviation_settings
Create Date: 2026-07-22 08:08:44.725867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0048_make_rule_id_nullable_in_energy_alert'
down_revision: Union[str, None] = '0047_add_energy_daily_data_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS energy')
    op.alter_column('energy_alert_records', 'rule_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='预警规则ID',
               schema='energy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_alert_records', 'rule_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='预警规则ID',
               schema='energy')
    # ### end Alembic commands ###
