"""add_equipment_model_changes

Revision ID: 0049_add_equipment_model_changes
Revises: 0048_make_rule_id_nullable_in_energy_alert
Create Date: 2026-07-28 09:00:24.187680
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0049_add_equipment_model_changes'
down_revision: Union[str, None] = '0048_make_rule_id_nullable_in_energy_alert'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS equipment')
    op.drop_index(op.f('uq_equipment_categories_code_dept'), table_name='equipment_categories', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_equipment_categories_code', 'equipment_categories', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('equipment_categories', 'department_id', schema='equipment')
    op.drop_index(op.f('uq_equipment_category_links'), table_name='equipment_category_links', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_category_links', 'equipment_category_links', ['equipment_id', 'category_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_personnel_category'), table_name='equipment_personnel_category', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_personnel_category', 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_personnel_role'), table_name='equipment_personnel_role', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_personnel_role', 'equipment_personnel_role', ['personnel_id', 'role_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_role_code'), table_name='equipment_role', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_role_code', 'equipment_role', ['code'], schema='equipment')
    op.create_unique_constraint(None, 'equipment_role', ['code'], schema='equipment')
    op.add_column('equipments', sa.Column('responsible_person_name', sa.String(length=100), nullable=True, comment='负责人姓名'), schema='equipment')
    op.drop_index(op.f('uq_equipments_asset_no'), table_name='equipments', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipments_asset_no', 'equipments', ['asset_no', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_route_equipments_route_equipment'), table_name='inspection_route_equipments', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_route_equipments_route_equipment', 'inspection_route_equipments', ['route_id', 'equipment_id', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_route_schedules_route_cron_deleted'), table_name='inspection_route_schedules', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', ['route_id', 'cron_expression', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_inspection_routes_name'), table_name='inspection_routes', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_inspection_routes_name', 'inspection_routes', ['name', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_inspection_tasks_task_no'), table_name='inspection_tasks', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_inspection_tasks_task_no', 'inspection_tasks', ['task_no', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_locations_code_dept'), table_name='locations', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_locations_code', 'locations', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('locations', 'department_id', schema='equipment')
    op.add_column('maintenance_plans', sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID'), schema='equipment')
    op.alter_column('maintenance_plans', 'equipment_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='设备ID',
               existing_comment='设备ID（与 category_id 二选一）',
               schema='equipment')
    op.drop_constraint(op.f('maintenance_plans_executor_id_fkey'), 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_plans', 'users', ['responsible_person_id'], ['id'], source_schema='equipment', referent_schema='identity')
    op.drop_column('maintenance_plans', 'executor_id', schema='equipment')
    op.drop_column('maintenance_plans', 'category_id', schema='equipment')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_comment='工单类型：故障维修/计划维护/校准/异常处理/日常维护',
               existing_nullable=False,
               schema='equipment')
    op.drop_index(op.f('uq_work_orders_work_order_no'), table_name='work_orders', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_work_orders_work_order_no', 'work_orders', ['work_order_no', 'is_deleted'], schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_work_orders_work_order_no', 'work_orders', schema='equipment', type_='unique')
    op.create_index(op.f('uq_work_orders_work_order_no'), 'work_orders', ['work_order_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/计划维护/校准/异常处理/日常维护',
               existing_comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_nullable=False,
               schema='equipment')
    op.add_column('maintenance_plans', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True, comment='设备分类ID（与 equipment_id 二选一）'), schema='equipment')
    op.add_column('maintenance_plans', sa.Column('executor_id', sa.UUID(), autoincrement=False, nullable=True, comment='执行人ID'), schema='equipment')
    op.drop_constraint(None, 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_plans_executor_id_fkey'), 'maintenance_plans', 'users', ['executor_id'], ['id'], source_schema='equipment', referent_schema='identity')
    op.alter_column('maintenance_plans', 'equipment_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='设备ID（与 category_id 二选一）',
               existing_comment='设备ID',
               schema='equipment')
    op.drop_column('maintenance_plans', 'responsible_person_id', schema='equipment')
    op.add_column('locations', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index('uq_locations_code', table_name='locations', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_locations_code_dept'), 'locations', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_inspection_tasks_task_no', 'inspection_tasks', schema='equipment', type_='unique')
    op.create_index(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', ['task_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_inspection_routes_name', 'inspection_routes', schema='equipment', type_='unique')
    op.create_index(op.f('uq_inspection_routes_name'), 'inspection_routes', ['name'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', schema='equipment', type_='unique')
    op.create_index(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', ['route_id', 'cron_expression'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_route_equipments_route_equipment', 'inspection_route_equipments', schema='equipment', type_='unique')
    op.create_index(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', ['route_id', 'equipment_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipments_asset_no', 'equipments', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipments_asset_no'), 'equipments', ['asset_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('equipments', 'responsible_person_name', schema='equipment')
    op.drop_constraint(None, 'equipment_role', schema='equipment', type_='unique')
    op.drop_constraint('uq_equipment_role_code', 'equipment_role', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_role_code'), 'equipment_role', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_personnel_role', 'equipment_personnel_role', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', ['personnel_id', 'role_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_personnel_category', 'equipment_personnel_category', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_category_links', 'equipment_category_links', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_category_links'), 'equipment_category_links', ['equipment_id', 'category_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.add_column('equipment_categories', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index('uq_equipment_categories_code', table_name='equipment_categories', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_equipment_categories_code_dept'), 'equipment_categories', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    # ### end Alembic commands ###
