"""0053_add_energy_unit_consumption_targets

Revision ID: 0053
Revises: 0052_add_dossier_unique_indexes_and_cleanup
Create Date: 2026-08-07 15:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0053_add_energy_unit_consumption_targets'
down_revision: Union[str, None] = '0052_add_dossier_unique_indexes_and_cleanup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_unit_consumption_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workshop_id', sa.Uuid(), nullable=False, comment='关联车间ID'),
    sa.Column('target_month', sa.Date(), nullable=False, comment='目标月份'),
    sa.Column('target_unit_consumption', sa.Numeric(precision=10, scale=4), nullable=False, comment='目标单耗(kWh/件)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['energy.energy_workshops.id'], ondelete='CASCADE', name='fk_target_workshop'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'target_month', name='uk_workshop_month'),
    schema='energy',
    comment='车间单耗目标表'
    )
    op.create_index('idx_workshop_id', 'energy_unit_consumption_targets', ['workshop_id'], schema='energy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workshop_id', table_name='energy_unit_consumption_targets', schema='energy')
    op.drop_table('energy_unit_consumption_targets', schema='energy')
    # ### end Alembic commands ###
