"""add capa table

Revision ID: 0061_add_capa_table
Revises: 0060_add_foreign_keys_and_fix_nullable
Create Date: 2026-09-23 08:49:51.802149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0061_add_capa_table'
down_revision: Union[str, None] = '0060_add_foreign_keys_and_fix_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS quality')
    op.create_table('capas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capa_code', sa.String(length=255), nullable=False),
    sa.Column('final_code', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('deviation_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_code', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('root_cause_category', sa.String(length=255), nullable=True),
    sa.Column('non_conformity_description', sa.Text(), nullable=True),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('root_cause_attachments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('reason_category', sa.String(length=255), nullable=True),
    sa.Column('capa_content', sa.Text(), nullable=True),
    sa.Column('capa_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('expected_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qa_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('qa_review_opinion', sa.Text(), nullable=True),
    sa.Column('qa_review_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('q_head_approver_id', sa.UUID(), nullable=True),
    sa.Column('q_head_approval_opinion', sa.Text(), nullable=True),
    sa.Column('q_head_approval_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_status', sa.Text(), nullable=True),
    sa.Column('execution_tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dept_head_confirmations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_result', sa.Text(), nullable=True),
    sa.Column('evaluation_target', sa.Text(), nullable=True),
    sa.Column('evaluation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_confirmer_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_confirm_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_remark', sa.Text(), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('report_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('returned_step', sa.String(length=50), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporter', sa.String(length=255), nullable=True),
    sa.Column('qa_confirmer', sa.String(length=255), nullable=True),
    sa.Column('qa_confirm_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['deviation_id'], ['quality.quality_deviations.id'], ),
    sa.ForeignKeyConstraint(['evaluation_confirmer_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['q_head_approver_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['qa_reviewer_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capa_code'),
    schema='quality'
    )
    op.create_index('idx_capa_code', 'capas', ['capa_code'], unique=True, schema='quality')
    op.create_index('idx_capa_deviation_id', 'capas', ['deviation_id'], unique=False, schema='quality')
    op.create_index('idx_capa_status', 'capas', ['status'], unique=False, schema='quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_capa_status', table_name='capas', schema='quality')
    op.drop_index('idx_capa_deviation_id', table_name='capas', schema='quality')
    op.drop_index('idx_capa_code', table_name='capas', schema='quality')
    op.drop_table('capas', schema='quality')
    # ### end Alembic commands ###
