"""Add EnergyDailyData table

Revision ID: 78dece9ae0a3
Revises: 49684887bf7e
Create Date: 2026-07-22 08:02:02.952294
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78dece9ae0a3'
down_revision: Union[str, None] = '49684887bf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS energy')
    op.execute('CREATE SCHEMA IF NOT EXISTS equipment')
    op.execute('CREATE SCHEMA IF NOT EXISTS safety')
    op.create_table('energy_daily_data',
    sa.Column('date', sa.Date(), nullable=False, comment='数据日期'),
    sa.Column('energy_type', sa.String(length=20), nullable=False, comment='能源类型: water/electricity/steam/natural_gas'),
    sa.Column('category', sa.String(length=50), nullable=False, comment="类别（如'水（吨）'）"),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False, comment='总数（实际用量）'),
    sa.Column('alert_threshold', sa.Numeric(precision=18, scale=4), nullable=False, comment='警戒线（预警阈值）'),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True, comment='费用'),
    sa.Column('municipal_meter', sa.Numeric(precision=18, scale=4), nullable=True, comment='市政总表'),
    sa.Column('error_value', sa.Numeric(precision=18, scale=4), nullable=True, comment='误差'),
    sa.Column('source_table', sa.String(length=50), nullable=False, comment='来源表（水表/电表等）'),
    sa.Column('is_alert', sa.Boolean(), nullable=False, comment='是否触发预警'),
    sa.Column('alert_record_id', sa.UUID(), nullable=True, comment='关联预警记录ID'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'energy_type', 'category', name='uq_energy_daily_data_date_type_category'),
    schema='energy'
    )
    op.drop_table('hazard_revision_archives', schema='safety')
    op.drop_table('api_call_configs', schema='safety')
    op.drop_index(op.f('uq_scheduled_tasks_name'), table_name='scheduled_tasks', schema='safety', postgresql_where='(is_deleted = false)')
    op.drop_table('scheduled_tasks', schema='safety')
    op.drop_index(op.f('uq_ai_workflow_config_module_code'), table_name='ai_workflow_configs', schema='safety', postgresql_where='(is_deleted = false)')
    op.drop_table('ai_workflow_configs', schema='safety')
    op.drop_table('scheduled_task_logs', schema='safety')
    op.drop_table('hazard_revision_records', schema='safety')
    op.drop_index(op.f('uq_equipment_categories_code_dept'), table_name='equipment_categories', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_equipment_categories_code', 'equipment_categories', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('equipment_categories', 'department_id', schema='equipment')
    op.drop_index(op.f('uq_equipment_category_links'), table_name='equipment_category_links', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_category_links', 'equipment_category_links', ['equipment_id', 'category_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_personnel_category'), table_name='equipment_personnel_category', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_personnel_category', 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_personnel_role'), table_name='equipment_personnel_role', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_personnel_role', 'equipment_personnel_role', ['personnel_id', 'role_id'], schema='equipment')
    op.drop_index(op.f('uq_equipment_role_code'), table_name='equipment_role', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipment_role_code', 'equipment_role', ['code'], schema='equipment')
    op.create_unique_constraint(None, 'equipment_role', ['code'], schema='equipment')
    op.add_column('equipments', sa.Column('responsible_person_name', sa.String(length=100), nullable=True, comment='负责人姓名'), schema='equipment')
    op.drop_index(op.f('uq_equipments_asset_no'), table_name='equipments', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_equipments_asset_no', 'equipments', ['asset_no', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_route_equipments_route_equipment'), table_name='inspection_route_equipments', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_route_equipments_route_equipment', 'inspection_route_equipments', ['route_id', 'equipment_id', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_route_schedules_route_cron_deleted'), table_name='inspection_route_schedules', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', ['route_id', 'cron_expression', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_inspection_routes_name'), table_name='inspection_routes', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_inspection_routes_name', 'inspection_routes', ['name', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_inspection_tasks_task_no'), table_name='inspection_tasks', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_inspection_tasks_task_no', 'inspection_tasks', ['task_no', 'is_deleted'], schema='equipment')
    op.drop_index(op.f('uq_locations_code_dept'), table_name='locations', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_index('uq_locations_code', 'locations', ['code'], unique=True, schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_column('locations', 'department_id', schema='equipment')
    op.add_column('maintenance_plans', sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID'), schema='equipment')
    op.alter_column('maintenance_plans', 'equipment_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='设备ID',
               existing_comment='设备ID（与 category_id 二选一）',
               schema='equipment')
    op.drop_constraint(op.f('maintenance_plans_executor_id_fkey'), 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_plans', 'users', ['responsible_person_id'], ['id'], source_schema='equipment', referent_schema='identity')
    op.drop_column('maintenance_plans', 'category_id', schema='equipment')
    op.drop_column('maintenance_plans', 'executor_id', schema='equipment')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_comment='工单类型：故障维修/计划维护/校准/异常处理/日常维护',
               existing_nullable=False,
               schema='equipment')
    op.drop_index(op.f('uq_work_orders_work_order_no'), table_name='work_orders', schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_unique_constraint('uq_work_orders_work_order_no', 'work_orders', ['work_order_no', 'is_deleted'], schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_work_orders_work_order_no', 'work_orders', schema='equipment', type_='unique')
    op.create_index(op.f('uq_work_orders_work_order_no'), 'work_orders', ['work_order_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/计划维护/校准/异常处理/日常维护',
               existing_comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_nullable=False,
               schema='equipment')
    op.add_column('maintenance_plans', sa.Column('executor_id', sa.UUID(), autoincrement=False, nullable=True, comment='执行人ID'), schema='equipment')
    op.add_column('maintenance_plans', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True, comment='设备分类ID（与 equipment_id 二选一）'), schema='equipment')
    op.drop_constraint(None, 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_plans_executor_id_fkey'), 'maintenance_plans', 'users', ['executor_id'], ['id'], source_schema='equipment', referent_schema='identity')
    op.alter_column('maintenance_plans', 'equipment_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='设备ID（与 category_id 二选一）',
               existing_comment='设备ID',
               schema='equipment')
    op.drop_column('maintenance_plans', 'responsible_person_id', schema='equipment')
    op.add_column('locations', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index('uq_locations_code', table_name='locations', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_locations_code_dept'), 'locations', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_inspection_tasks_task_no', 'inspection_tasks', schema='equipment', type_='unique')
    op.create_index(op.f('uq_inspection_tasks_task_no'), 'inspection_tasks', ['task_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_inspection_routes_name', 'inspection_routes', schema='equipment', type_='unique')
    op.create_index(op.f('uq_inspection_routes_name'), 'inspection_routes', ['name'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_route_schedules_route_cron_deleted', 'inspection_route_schedules', schema='equipment', type_='unique')
    op.create_index(op.f('uq_route_schedules_route_cron_deleted'), 'inspection_route_schedules', ['route_id', 'cron_expression'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_route_equipments_route_equipment', 'inspection_route_equipments', schema='equipment', type_='unique')
    op.create_index(op.f('uq_route_equipments_route_equipment'), 'inspection_route_equipments', ['route_id', 'equipment_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipments_asset_no', 'equipments', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipments_asset_no'), 'equipments', ['asset_no'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_column('equipments', 'responsible_person_name', schema='equipment')
    op.drop_constraint(None, 'equipment_role', schema='equipment', type_='unique')
    op.drop_constraint('uq_equipment_role_code', 'equipment_role', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_role_code'), 'equipment_role', ['code'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_personnel_role', 'equipment_personnel_role', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_personnel_role'), 'equipment_personnel_role', ['personnel_id', 'role_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_personnel_category', 'equipment_personnel_category', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_personnel_category'), 'equipment_personnel_category', ['personnel_id', 'role_id', 'category_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.drop_constraint('uq_equipment_category_links', 'equipment_category_links', schema='equipment', type_='unique')
    op.create_index(op.f('uq_equipment_category_links'), 'equipment_category_links', ['equipment_id', 'category_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.add_column('equipment_categories', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    op.drop_index('uq_equipment_categories_code', table_name='equipment_categories', schema='equipment', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('uq_equipment_categories_code_dept'), 'equipment_categories', ['code', 'department_id'], unique=True, schema='equipment', postgresql_where='(is_deleted = false)')
    op.create_table('hazard_revision_records',
    sa.Column('hazard_revision_no', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='危害修订编号'),
    sa.Column('regulation_revision_id', sa.UUID(), autoincrement=False, nullable=True, comment='法规修订ID'),
    sa.Column('regulation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='法规名称'),
    sa.Column('identifier_id', sa.UUID(), autoincrement=False, nullable=True, comment='识别器ID'),
    sa.Column('identifier_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='识别器名称'),
    sa.Column('identification_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='识别时间'),
    sa.Column('identification_type', sa.VARCHAR(length=32), server_default=sa.text("'auto_trigger'::character varying"), autoincrement=False, nullable=False, comment='识别类型'),
    sa.Column('process_change_content', sa.TEXT(), autoincrement=False, nullable=True, comment='工艺变更内容'),
    sa.Column('identification_scope', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='识别范围'),
    sa.Column('review_opinion', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='审查意见'),
    sa.Column('hazard_document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='危害文档路径'),
    sa.Column('hazard_document_original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='危害文档原始名称'),
    sa.Column('linked_hazard_archive_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的危害归档ID'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('hazard_revision_records_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('hazard_revision_records_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hazard_revision_records_pkey')),
    schema='safety'
    )
    op.create_table('scheduled_task_logs',
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False, comment='关联 scheduled_tasks.id'),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='开始执行时间'),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='完成时间'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=False, comment='执行状态: running/success/failure'),
    sa.Column('data_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='聚合数据快照'),
    sa.Column('card_content', sa.TEXT(), autoincrement=False, nullable=True, comment='发送的卡片 JSON 内容'),
    sa.Column('feishu_msg_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='飞书返回的消息 ID'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='执行耗时（毫秒）'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('scheduled_task_logs_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('scheduled_task_logs_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_task_logs_pkey')),
    schema='safety'
    )
    op.create_table('ai_workflow_configs',
    sa.Column('module_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='模块代码（hazard-identification / regulation / hazard 等）'),
    sa.Column('workflow_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='工作流名称'),
    sa.Column('workflow_description', sa.TEXT(), autoincrement=False, nullable=True, comment='工作流描述'),
    sa.Column('trigger_event', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='触发事件（submit / revision_created 等）'),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('script_configs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='脚本配置 JSON 数组'),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='排序顺序'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('ai_workflow_configs_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('ai_workflow_configs_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_workflow_configs_pkey')),
    schema='safety',
    comment='AI 工作流配置表'
    )
    op.create_index(op.f('uq_ai_workflow_config_module_code'), 'ai_workflow_configs', ['module_code'], unique=True, schema='safety', postgresql_where='(is_deleted = false)')
    op.create_table('scheduled_tasks',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='任务名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='任务描述'),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Cron 表达式，如 0 9 * * *'),
    sa.Column('cron_desc', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Cron 可读描述，如「每天上午9点」'),
    sa.Column('feishu_chat_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='目标飞书群聊 chat_id'),
    sa.Column('feishu_chat_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='飞书群聊名称快照'),
    sa.Column('header_color', sa.VARCHAR(length=20), server_default=sa.text("'blue'::character varying"), autoincrement=False, nullable=False, comment='卡片头部颜色: blue/orange/green/red/purple'),
    sa.Column('data_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='数据来源配置'),
    sa.Column('card_template', sa.TEXT(), autoincrement=False, nullable=True, comment='消息卡片 Markdown 模板'),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='上次执行时间'),
    sa.Column('last_run_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='上次执行状态: success/failure'),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True, comment='上次错误信息'),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='下次执行时间'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('scheduled_tasks_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('scheduled_tasks_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_tasks_pkey')),
    schema='safety'
    )
    op.create_index(op.f('uq_scheduled_tasks_name'), 'scheduled_tasks', ['name'], unique=True, schema='safety', postgresql_where='(is_deleted = false)')
    op.create_table('api_call_configs',
    sa.Column('config_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='配置名称'),
    sa.Column('api_base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='API基础URL'),
    sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='API密钥'),
    sa.Column('model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='模型名称'),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.1'::double precision"), autoincrement=False, nullable=False, comment='温度参数'),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('120'), autoincrement=False, nullable=False, comment='超时秒数'),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='最大Token数'),
    sa.Column('extra_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='额外配置JSON'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否激活'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('api_call_configs_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('api_call_configs_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_call_configs_pkey')),
    schema='safety'
    )
    op.create_table('hazard_revision_archives',
    sa.Column('regulation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='法规名称'),
    sa.Column('hazard_document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='危害文档路径'),
    sa.Column('hazard_document_original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='危害文档原始名称'),
    sa.Column('identification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='识别日期'),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], name=op.f('hazard_revision_archives_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], name=op.f('hazard_revision_archives_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hazard_revision_archives_pkey')),
    schema='safety'
    )
    op.drop_table('energy_daily_data', schema='energy')
    # ### end Alembic commands ###
