"""0043_fix_production_index_names

Revision ID: fcb768b8df78
Revises: 2eb6d687679e
Create Date: 2026-07-15 18:02:28.635344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb768b8df78'
down_revision: Union[str, None] = '2eb6d687679e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS production')
    op.drop_index(op.f('ix_product_outputs_product_id'), table_name='product_outputs', schema='production')
    op.drop_index(op.f('ix_product_outputs_production_date'), table_name='product_outputs', schema='production')
    op.drop_index(op.f('ix_product_outputs_workshop'), table_name='product_outputs', schema='production')
    op.create_index(op.f('ix_production_product_outputs_product_id'), 'product_outputs', ['product_id'], unique=False, schema='production')
    op.create_index(op.f('ix_production_product_outputs_workshop'), 'product_outputs', ['workshop'], unique=False, schema='production')
    op.drop_index(op.f('ix_products_workshop'), table_name='products', schema='production')
    op.create_index(op.f('ix_production_products_workshop'), 'products', ['workshop'], unique=False, schema='production')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_products_workshop'), table_name='products', schema='production')
    op.create_index(op.f('ix_products_workshop'), 'products', ['workshop'], unique=False, schema='production')
    op.drop_index(op.f('ix_production_product_outputs_workshop'), table_name='product_outputs', schema='production')
    op.drop_index(op.f('ix_production_product_outputs_product_id'), table_name='product_outputs', schema='production')
    op.create_index(op.f('ix_product_outputs_workshop'), 'product_outputs', ['workshop'], unique=False, schema='production')
    op.create_index(op.f('ix_product_outputs_production_date'), 'product_outputs', ['production_date'], unique=False, schema='production')
    op.create_index(op.f('ix_product_outputs_product_id'), 'product_outputs', ['product_id'], unique=False, schema='production')
    # ### end Alembic commands ###
