'use client'
// production module components
export { default as LabelVerificationClient } from './LabelVerificationClient'
export { BalancePageClient } from './BalancePageClient'
export { BatchesPageClient } from './BatchesPageClient'
export { PlanPageClient } from './PlanPageClient'
export { PressurePageClient } from './PressurePageClient'
export { ProcessPageClient } from './ProcessPageClient'
export { ProductionDashboardClient } from './ProductionDashboardClient'
export { RecordsPageClient } from './RecordsPageClient'
export { PressureAuditPageClient } from './pressure/PressureAuditPageClient'
export { PressureManualInputPageClient } from './pressure/PressureManualInputPageClient'
export { PressureOcrInputPageClient } from './pressure/PressureOcrInputPageClient'
export { PressurePointManagementPageClient } from './pressure/PressurePointManagementPageClient'
export { PressureRecordsPageClient } from './pressure/PressureRecordsPageClient'
export { default as WorkshopRankingTrend } from './WorkshopRankingTrend'
export * from './product'
