import { test, expect } from '@playwright/test'

const ROUTES = [
  '/administration',
  '/administration/approval',
  '/administration/it-tickets',
  '/administration/login-logs',
  '/administration/meeting',
  '/administration/meeting/ledger',
  '/administration/meeting/requests',
  '/administration/meeting/requisitions',
  '/administration/notice',
  '/administration/vehicle-requests',
  '/administration/vehicles',
  '/energy',
  '/energy/alerts',
  '/energy/collect-logs',
  '/energy/devices',
  '/energy/monthly',
  '/energy/settings',
  '/energy/workshops',
  '/environment',
  '/equipment',
  '/equipment/assets',
  '/equipment/inspection',
  '/equipment/maintenance',
  '/equipment/personnel',
  '/equipment/settings',
  '/equipment/spare-parts',
  '/equipment/stats',
  '/hr',
  '/hr/attendance',
  '/hr/departments',
  '/hr/departure',
  '/hr/new/departments',
  '/hr/new/departure',
  '/hr/new/offboarding',
  '/hr/new/onboarding',
  '/hr/new/profile',
  '/hr/offboarding',
  '/hr/onboarding',
  '/hr/profile',
  '/hr/recruitment',
  '/hr/roster',
  '/hr/settings',
  '/hr/system/settings',
  '/hr/training',
  '/hr/training/ai-exam',
  '/hr/training/annual-plan',
  '/hr/training/annual-plan/new',
  '/hr/training/evaluation-form',
  '/hr/training/ledger',
  '/hr/training/ledger/new',
  '/hr/training/notification',
  '/hr/training/onboarding',
  '/hr/training/records',
  '/hr/training/select-tasks',
  '/hr/training/sign-in',
  '/hr/training/sop-catalog',
  '/hr/training/specialists',
  '/hr/training/trainers',
  '/procurement',
  '/procurement/contract-summary',
  '/procurement/invoice-recognition',
  '/procurement/order',
  '/procurement/supplier',
  '/production',
  '/production/balance',
  '/production/batches',
  '/production/label-verification',
  '/production/plan',
  '/production/pressure',
  '/production/pressure/audit',
  '/production/pressure/manual-input',
  '/production/pressure/ocr-input',
  '/production/pressure/point-management',
  '/production/pressure/records',
  '/production/process',
  '/production/product-output',
  '/production/product-output/all-products',
  '/production/records',
  '/quality',
  '/quality/ai-config',
  '/quality/ai-log',
  '/quality/calculator',
  '/quality/cpv',
  '/quality/department-contacts',
  '/quality/deviation',
  '/quality/deviation-automation/create',
  '/quality/deviation-automation/history',
  '/quality/deviation-automation/sop',
  '/quality/deviation-automation/templates',
  '/quality/deviation-flow/create',
  '/quality/deviation-flow/progress',
  '/quality/deviation-flow/query',
  '/quality/deviation-flow/settings',
  '/quality/deviation/report',
  '/quality/doc-check',
  '/quality/doc-check/new',
  '/quality/fqc',
  '/quality/inspection',
  '/quality/inspection/standards',
  '/quality/inspection-table',
  '/quality/instrument',
  '/quality/instrument/list',
  '/quality/instrument/list/create',
  '/quality/instrument/list/edit',
  '/quality/instrument/records',
  '/quality/instrument/settings',
  '/quality/ipqc',
  '/quality/iqc',
  '/quality/material-report',
  '/quality/material-report/create',
  '/quality/material-report/template',
  '/quality/reagent',
  '/quality/reagent/reminder',
  '/quality/retention',
  '/quality/sampling',
  '/quality/sop-ai/batch',
  '/quality/sop-ai/preview',
  '/quality/sop-ai/records',
  '/quality/stability',
  '/quality/stability/plan',
  '/quality/stability/report',
  '/quality/stability/result',
  '/quality/stability/settings',
  '/quality/static-data',
  '/quality/static-data/audit',
  '/quality/static-data/chrom-column',
  '/quality/static-data/hplc-reference',
  '/quality/static-data/medium',
  '/quality/static-data/standard',
  '/quality/static-data/storage-condition',
  '/registration',
  '/registration/authorization-letter',
  '/registration/dossier-writer',
  '/registration/ledger',
  '/registration/projects',
  '/registration/reference-standard',
  '/registration/regulation',
  '/registration/regulation/list',
  '/registration/review',
  '/registration/supplementary-reply',
  '/registration/validation-audit',
  '/registration/validation-audit/new',
  '/research',
  '/research/bayesian',
  '/research/deliverable-templates',
  '/research/ich-analysis',
  '/research/initiations',
  '/research/pilot-workflow',
  '/research/process-optimization',
  '/research/process-validation',
  '/research/projects',
  '/research/registration-filing',
  '/research/reports',
  '/research/research-tracks',
  '/research/route-development',
  '/safety',
  '/safety/accident',
  '/safety/check',
  '/safety/contractor',
  '/safety/ehs-change',
  '/safety/hazard',
  '/safety/hazard-identification',
  '/safety/hazard-identification/ledger',
  '/safety/hazard-identification/new',
  '/safety/hazard-ledger',
  '/safety/knowledge-base',
  '/safety/knowledge-base/graph',
  '/safety/occupational-health',
  '/safety/regulation',
  '/safety/regulation/generator',
  '/safety/risk-reporting',
  '/safety/settings',
  '/safety/special-ops',
  '/safety/special-ops/personnel',
  '/safety/training',
  '/settings',
  '/warehouse',
  '/warehouse/feishu-config',
  '/warehouse/packaging',
  '/warehouse/product',
  '/warehouse/raw-material',
]

test.describe('路由冒烟测试', () => {
  for (const path of ROUTES) {
    test(`${path} 页面加载`, async ({ page }) => {
      test.setTimeout(30000)

      const httpErrors: string[] = []
      const failedRequests: string[] = []

      page.on('response', (response) => {
        if (response.url().includes('/api/') && response.status() >= 400) {
          httpErrors.push(
            `[${response.status()}] ${response.request().method()} ${response.url()}`,
          )
        }
      })

      page.on('requestfailed', (request) => {
        const url = request.url()
        if (url.includes('/api/')) {
          failedRequests.push(
            `${request.method()} ${url}: ${request.failure()?.errorText ?? 'unknown error'}`,
          )
        }
      })

      const response = await page.goto(path)
      expect(response?.status()).toBe(200)

      await expect(page.locator('h1, h2, h3, h4').first()).toBeVisible({ timeout: 10000 })

      await expect(page.getByText('页面加载出错')).not.toBeVisible()
      await expect(page.getByText('应用加载出错')).not.toBeVisible()

      expect(httpErrors, `Unexpected API errors on ${path}:\n${httpErrors.join('\n')}`).toEqual([])
      expect(failedRequests, `Failed requests on ${path}:\n${failedRequests.join('\n')}`).toEqual([])
    })
  }
})
